# Generated by Django 4.1 on 2022-08-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_curso_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregable',
            name='entregado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='entregable',
            name='fecha_entrega',
            field=models.CharField(max_length=50),
        ),
    ]
