# Generated by Django 4.1 on 2022-08-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_alter_entregable_fecha_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregable',
            name='fecha_entrega',
            field=models.CharField(max_length=50),
        ),
    ]
